"""AL_WEEK4_24_2_bt2.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1alBg-oDOZ157gjdmImL6p9GN-iV3qTt5
"""
"""trước tiên phải cài lệnh
pip install scikit-fuzzy"""

import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt
from skfuzzy import control as ctrl
time=ctrl.Antecedent(np.arange(10,181,1),'time')
rice=ctrl.Antecedent(np.arange(200,2001,1),'rice')
power=ctrl.Consequent(np.arange(0,101,1),'power')

time['veryfast']=fuzz.trimf(time.universe,[10,10,20])
time['fast']=fuzz.trimf(time.universe,[15,20,30])
time['medium']=fuzz.trimf(time.universe,[25,30,60])
time['slow']=fuzz.trimf(time.universe,[50,80,100])
time['veryslow']=fuzz.trimf(time.universe,[90,150,180])

rice['veryless']=fuzz.trimf(rice.universe,[200,200,500])
rice['less']=fuzz.trimf(rice.universe,[400,600,800])
rice['medium']=fuzz.trimf(rice.universe,[700,900,1000])
rice['much']=fuzz.trimf(rice.universe,[900,1400,1600])
rice['verymuch']=fuzz.trimf(rice.universe,[1500,1800,2000])

power['verylow']=fuzz.trimf(power.universe,[0,15,30])
power['low']=fuzz.trimf(power.universe,[20,35,45])
power['balance']=fuzz.trimf(power.universe,[40,50,60])
power['high']=fuzz.trimf(power.universe,[55,70,80])
power['veryhigh']=fuzz.trimf(power.universe,[75,80,100])

rule1=ctrl.Rule(time['veryfast']&rice['veryless'],power['verylow'])
rule2=ctrl.Rule(time['veryfast']&rice['less'],power['verylow'])
rule3=ctrl.Rule(time['veryfast']&rice['medium'],power['low'])
rule4=ctrl.Rule(time['veryfast']&rice['much'],power['balance'])
rule5=ctrl.Rule(time['veryfast']&rice['verymuch'],power['balance'])
rule6=ctrl.Rule(time['fast']&rice['veryless'],power['verylow'])
rule7=ctrl.Rule(time['fast']&rice['less'],power['low'])
rule8=ctrl.Rule(time['fast']&rice['medium'],power['balance'])
rule9=ctrl.Rule(time['fast']&rice['much'],power['high'])
rule10=ctrl.Rule(time['fast']&rice['verymuch'],power['veryhigh'])
rule11=ctrl.Rule(time['medium']&rice['veryless'],power['low'])
rule12=ctrl.Rule(time['medium']&rice['less'],power['balance'])
rule13=ctrl.Rule(time['medium']&rice['medium'],power['high'])
rule14=ctrl.Rule(time['medium']&rice['much'],power['high'])
rule15=ctrl.Rule(time['medium']&rice['verymuch'],power['high'])
rule16=ctrl.Rule(time['slow']&rice['veryless'],power['balance'])
rule17=ctrl.Rule(time['slow']&rice['less'],power['high'])
rule18=ctrl.Rule(time['slow']&rice['medium'],power['high'])
rule19=ctrl.Rule(time['slow']&rice['much'],power['high'])
rule20=ctrl.Rule(time['slow']&rice['verymuch'],power['veryhigh'])
rule21=ctrl.Rule(time['veryslow']&rice['veryless'],power['balance'])
rule22=ctrl.Rule(time['veryslow']&rice['less'],power['high'])
rule23=ctrl.Rule(time['veryslow']&rice['medium'],power['high'])
rule24=ctrl.Rule(time['veryslow']&rice['much'],power['veryhigh'])
rule25=ctrl.Rule(time['veryslow']&rice['verymuch'],power['veryhigh'])
powering_ctrl = ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5,rule6,rule7,rule8,rule9,rule10,rule11,rule12,rule13,rule14,rule15,rule16,rule17,rule18,rule19,rule20,rule21,rule22,rule23,rule23,rule24,rule25])
powering = ctrl.ControlSystemSimulation(powering_ctrl)
powering.input['time']=170
powering.input['rice']=1800
powering.compute()
print(powering.output['power'])
power.view(sim=powering)
